export default [
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 1,
  },
  {
    img: "https://m.media-amazon.com/images/I/41xfzQ2MeAL._SX300_SY300_QL70_FMwebp_.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 2,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 3,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 4,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 5,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 6,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 7,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 8,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 9,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 10,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 11,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 12,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 13,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 14,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 15,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 16,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 17,
  },
  {
    img: "https://m-cdn.phonearena.com/images/phones/74103-940/Apple-iPhone-X.jpg",
    name: "iPhoneX",
    price: 800000,
    rating: "⭐⭐⭐⭐⭐",
    description: "bhery nise phone",
    id: 18,
  },
];
